/* ═══════════════════════════════════════════════════════════════
   Single source of truth for all LAFODAP Nigeria projects.
   Used by the listing grid and every project detail page.
═══════════════════════════════════════════════════════════════ */

export const PROJECTS = [
  {
    slug: "uptown-skills-academy",
    hero: "/assets/hero-uptown.jpg",
    cat: "Education",
    img: "/assets/education-causes-img.jpg",
    title: "Uptown Skills Academy",
    loc: "Lagos & Abuja",
    desc: "Free after-school lessons and reading support for underprivileged children.",
    pct: 35,
    donors: 14, daysLeft: 41,
    summary: "A small, tuition-free learning space giving out-of-school children a structured path back into education, starting with reading, writing and numbers.",
    story: [
      "In many communities across Nigeria, children have never sat in a classroom. The Uptown Skills Academy offers free after-school lessons to children whose families cannot afford school fees.",
      "Lessons focus on the basics of reading, writing and mathematics, and each child has a volunteer tutor who checks in on their progress.",
      "With your support we can buy textbooks and learning materials and welcome another 10 children.",
    ],
    gallery: ["/assets/classroom-writing.jpg", "/assets/girls-reading.jpg", "/assets/school-children.jpg"],
    outcomes: [["18", "Children enrolled"], ["3", "Volunteer tutors"], ["2", "Lessons weekly"]],
    updates: [
      { date: "May 2026", text: "Welcomed 4 new pupils to the academy." },
      { date: "Feb 2026", text: "Received 2 donated laptops for lessons." },
    ],
  },
  {
    slug: "community-eye-screening",
    hero: "/assets/hero-eye.jpg",
    cat: "Health",
    img: "/assets/eye-screening.jpg",
    title: "Community Eye Screening",
    loc: "Lagos & Abuja",
    desc: "Free eye checks and reading glasses for adults and children.",
    pct: 20,
    donors: 9, daysLeft: 70,
    summary: "Free eye screening days with volunteer eye-care workers, reading glasses for those who need them, and referrals for anyone needing further treatment.",
    story: [
      "Poor eyesight often goes unchecked in low-income communities. Children struggle in class and adults lose the ability to work. Our screening days bring simple eye checks to people who have never had one.",
      "Volunteer eye-care workers test each person's vision, hand out reading glasses where needed, and refer anyone with a more serious condition to a clinic.",
      "Your gift pays for reading glasses, screening materials and transport for the volunteer team.",
    ],
    gallery: ["/assets/eye-exam-nigeria.jpg", "/assets/eye-exam-slitlamp.jpg", "/assets/medical-outreach.jpg"],
    outcomes: [["80", "People screened"], ["25", "Glasses given"], ["6", "Referrals"]],
    updates: [
      { date: "Apr 2026", text: "Held a screening day for 32 residents." },
    ],
  },
  {
    slug: "mobility-support",
    hero: "/assets/hero-mobility.jpg",
    cat: "Disability",
    img: "/assets/disability-causes-img.jpg",
    title: "Mobility Support Programme",
    loc: "Lagos & Abuja",
    desc: "Wheelchairs and walking aids for persons with disabilities.",
    pct: 30,
    donors: 11, daysLeft: 78,
    summary: "Getting persons with disabilities moving again with wheelchairs and walking aids, and the independence that comes with them.",
    story: [
      "For many persons with disabilities in Nigeria, a wheelchair is the difference between staying indoors and taking part in community life. We provide wheelchairs and walking aids to those who cannot afford them.",
      "Each recipient is shown how to use and care for their equipment, and we follow up to make sure it is still serving them well.",
      "Your gift funds the next wheelchair or walking aid, and helps someone get back to school, work and community life.",
    ],
    gallery: ["/assets/disability-assist.jpg", "/assets/women-group.jpg", "/assets/about-lafodap.jpg"],
    outcomes: [["10", "Wheelchairs given"], ["6", "Walking aids"], ["2", "Outreach days"]],
    updates: [
      { date: "Apr 2026", text: "Handed over 4 wheelchairs at our Ikorodu outreach." },
    ],
  },
  {
    slug: "women-in-trade",
    hero: "/assets/hero-women.jpg",
    cat: "Empowerment",
    img: "/assets/empowerment-causes2.jpg",
    title: "Women in Trade",
    loc: "Lagos & Abuja",
    desc: "Soap making, tailoring and starter kits for single mothers.",
    pct: 40,
    donors: 12, daysLeft: 33,
    summary: "Turning skills into income for single mothers through hands-on training in soap making and tailoring, starter kits and business mentoring.",
    story: [
      "A small trade can be the difference between dependency and dignity. Women in Trade teaches single mothers to make liquid soap and detergent, or to sew, so they can sell in their communities.",
      "Every participant receives a starter kit and three months of mentoring on pricing, record keeping and finding customers, so their business lasts.",
      "Help us train the next group of 6 women towards financial independence.",
    ],
    gallery: ["/assets/soap-making.jpg", "/assets/tailoring-women.jpg", "/assets/empowerment-causes.jpg"],
    outcomes: [["6", "Women per group"], ["3 mo", "Mentoring"], ["2", "Groups trained"]],
    updates: [
      { date: "Mar 2026", text: "A group of 5 women completed training with starter kits." },
    ],
  },
  {
    slug: "light-every-village",
    hero: "/assets/hero-light.jpg",
    cat: "Energy",
    img: "/assets/solar-lantern.jpg",
    title: "Light Every Home",
    loc: "Off-grid communities",
    desc: "Solar lanterns for families without power.",
    pct: 45,
    donors: 16, daysLeft: 19,
    summary: "Safe solar lanterns replacing kerosene lamps in off-grid homes, so children can study and families can breathe.",
    story: [
      "After dark, life stops in off-grid homes, or carries on by the smoky glow of a kerosene lamp. Light Every Home replaces those lamps with safe, rechargeable solar lanterns.",
      "Each lantern lets children study at night, keeps small businesses open longer, and removes the health hazard of indoor smoke.",
      "We're close to lighting another 8 homes. Your gift switches on the rest.",
    ],
    gallery: ["/assets/solar-lantern.jpg", "/assets/girls-reading.jpg", "/assets/girls-reading.jpg"],
    outcomes: [["20", "Homes lit"], ["90", "People reached"], ["0", "Kerosene fumes"]],
    updates: [
      { date: "Jun 2026", text: "Delivered solar lanterns to 4 new homes." },
      { date: "Jan 2026", text: "Reached 15 homes lit since launch." },
    ],
  },
  {
    slug: "orphan-sponsorship",
    hero: "/assets/kids-playing.jpg",
    cat: "Education",
    img: "/assets/sponsored-child.jpg",
    title: "Orphan Sponsorship",
    loc: "Across Nigeria",
    desc: "Sponsorship covering school fees, meals and care.",
    pct: 38,
    donors: 13, daysLeft: 52,
    summary: "Sponsorship that covers an orphaned child's school fees, meals and basic healthcare, with a caseworker who checks in regularly.",
    story: [
      "When a child loses their parents, they lose far more than family. They lose security, schooling and the small certainties of childhood. Our sponsorship programme helps restore all three.",
      "A sponsorship covers school fees, uniforms, daily meals and basic healthcare, and a caseworker visits each child regularly.",
      "Sponsor a child today and become the steady hand behind their future.",
    ],
    gallery: ["/assets/school-meal.jpg", "/assets/school-children.jpg", "/assets/about-lafodap.jpg"],
    outcomes: [["8", "Children sponsored"], ["100%", "Fees covered"], ["1", "Caseworker"]],
    updates: [
      { date: "May 2026", text: "Added 2 children to the sponsorship roll." },
    ],
  },
  {
    slug: "youth-mobility-grants",
    hero: "/assets/hero-youth.jpg",
    cat: "Empowerment",
    img: "/assets/mechanic-apprentice.jpg",
    title: "Youth Livelihood Grants",
    loc: "Lagos & Abuja",
    desc: "Starter tools that turn skills into livelihoods.",
    pct: 25,
    donors: 7, daysLeft: 60,
    summary: "Small grants for tools and starter stock that help a young person turn a trade they have learnt into a working livelihood.",
    story: [
      "A trained young person with no tools is still unemployed. Youth Livelihood Grants bridge that gap, giving apprentices the toolkit or starter stock they need to start earning.",
      "Recipients commit to a simple pledge: once established, they support the next young person in line, turning every grant into a chain of opportunity.",
      "Fund a grant and start that chain.",
    ],
    gallery: ["/assets/leather-work.jpg", "/assets/tailor-portrait.jpg", "/assets/empowerment-causes.jpg"],
    outcomes: [["5", "Grants given"], ["3", "Trades"], ["1", "Pay-it-forward pledge"]],
    updates: [
      { date: "Apr 2026", text: "Awarded 2 new starter grants." },
    ],
  },
];

export const CATS = ["All", "Education", "Health", "Disability", "Energy", "Empowerment"];

export const getProject = (slug) => PROJECTS.find((p) => p.slug === slug);
